version: 0.2
phases:
 install:
 runtime-versions:
 python: 3.8 # Specify the Python version you want to use
 commands:
 - echo "Installing dependencies..."
 # If there are no dependencies, you can skip the pip insta
 build:
 commands:
 - echo "Build started on $(date)"
 - python hello-world.py # Run the Python script
 post_build:
 commands:
 - echo "Build completed on $(date)"
 - echo "Hello World! Build completed successfully."

artifacts:
 files:
 - hello-world.py # Optional: specify the files you want to 
